### ISSUE TITLE
[BUG] Windows Automatic dependencies installation error

### ISSUE THREAD

**Issue by LavashVshocolade** [SebiAi/custom-nothing-glyph-tools#31]
Hi, I got an error when opening the bat file, The script will ask for administrator rights when you continue.
Do you want to continue? [y/n]: y
[INFO] The folder ".tmp" exists - using it.
[INFO] Please install/update AppInstaller from the Microsoft Store.

I installed everything according to the rules, I've been sitting here for two hours now and can't figure it out, it would be nice to get help. I feel stupid :(

**Comment by SebiAi** [comment]
> [INFO] Please install/update AppInstaller from the Microsoft Store.
1. Can you please send a screenshot of the terminal window?
2. Did the Microsoft Store open? If yes, can you also send a screenshot of the Microsoft Store page?
3. What happens if you open a terminal (<kbd>Win + R</kbd>, type `cmd` and press <kbd>Enter</kbd>) and execute `winget` - screenshot please

**Comment by SebiAi** [comment]
Closed due to inactivity
